### ISSUE TITLE
AdaptiveStore should use DI instead of initializing other stores by itself

### ISSUE THREAD

**Issue by BobrImperator** [simplabs/ember-simple-auth#2308]
It splits #2302
While working on #2306 we've discovered that store related tests are failing due to them not being isolated - after refactoring internals to use explicitly injected services and refactoring tests accordingly the tests would leak their instances to other tests in some cases e.g itBehavesLikeStore causes this to happen, this issue should make it easier to test AdaptiveStore

# TODOS
- [ ] register `session-store:cookie` `session-store:local-storage`
- [ ] use registered session-stores in AdaptiveStore directly
- [ ] refactor AdaptiveStore tests to use Ember DI
